# Site settings
title: George Do
email: contact.georgedo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  tÃ´i muá»‘n mÃ¬nh váº«n mÃ£i nhÆ° tháº¿, cÃ³ ngÆ°á»i há»i tÃ´i Ä‘Ã£ tá»«ng nÃ y tuá»•i rá»“i, khÃ´ng thá»ƒ bá»›t má»™t chÃºt â€œtá»± doâ€ Ä‘Æ°á»£c hay sao?ğŸ’­
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://geordo.github.io" # the base hostname & protocol for your site
twitter_username: georgedo_twit
github_username: geordo
linkedin_username: geordo

theme: minima

plugins:
  - jekyll-seo-tag